# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    msbuildArgs: '--runtime win10-x64'
- task: CmdLine@2
  displayName: 编译
  inputs:
    script: 'dotnet build --runtime win10-x64'

- task: ArchiveFiles@2
  displayName: 压缩文件
  inputs:
    rootFolderOrFile: 'd:\a\1\s\'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: FtpUpload@2
  displayName: FTP上传文件
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'file://47.105.214.235/wwwroot/'
    username: 'administrator'
    password: '931592457czA'
    rootDirectory: 'd:\a\1\a\'
    filePatterns: '*.zip'
    remoteDirectory: '/ServiceInstaller/$(Build.BuildId)/'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
